# Generated by Django 4.2.7 on 2023-11-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_collation="utf8mb3_general_ci",
                        db_column="상품명",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alc_type", models.TextField(db_column="주종")),
                ("alc_type_dropdown", models.TextField(db_column="세부 주종", null=True)),
                ("alc_ab", models.FloatField(db_column="절대 도수")),
                ("alc_range", models.IntegerField(db_column="상대 도수", null=True)),
                ("sweet", models.IntegerField(db_column="단맛")),
                ("body", models.IntegerField(db_column="바디감")),
                ("sour", models.IntegerField(db_column="신맛", null=True)),
                ("fizzy", models.IntegerField(db_column="청량감", null=True)),
                ("strong", models.IntegerField(db_column="향의 강도", null=True)),
                ("link_img", models.TextField(db_column="사진", null=True)),
            ],
            options={
                "db_table": "input",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="상품명",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alc_type", models.TextField(db_column="주종")),
                ("alc_ab", models.FloatField(db_column="절대 도수")),
                ("alc_range", models.IntegerField(db_column="상대 도수", null=True)),
                ("ml", models.IntegerField(db_column="용량")),
                ("price", models.IntegerField(db_column="가격")),
                ("CE", models.FloatField(db_column="가성비")),
                ("CE_good", models.IntegerField(db_column="맥주 가성비")),
                (
                    "name_sale",
                    models.TextField(blank=True, db_column="검색용 상품명", null=True),
                ),
                ("link_sale", models.TextField(blank=True, db_column="판매처", null=True)),
                ("sweet", models.IntegerField(db_column="단맛")),
                ("body", models.IntegerField(db_column="바디감")),
                ("sour", models.IntegerField(db_column="신맛", null=True)),
                ("fizzy", models.IntegerField(db_column="청량감", null=True)),
                ("strong", models.IntegerField(db_column="향의 강도", null=True)),
                ("scent", models.TextField(db_column="향의 종류")),
                ("link_img", models.TextField(db_column="사진", null=True)),
            ],
            options={
                "db_table": "output",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("age", models.CharField(max_length=2)),
                ("sex", models.BooleanField()),
                ("alc_type", models.CharField(max_length=3, null=True)),
                ("golm", models.TextField(null=True)),
                ("factor", models.IntegerField(null=True)),
                ("scent", models.TextField(null=True)),
                ("alc_range_bool", models.BooleanField(null=True)),
                ("CE_good_bool", models.BooleanField(null=True)),
                ("golajum", models.TextField(null=True)),
                ("login_id", models.CharField(max_length=10)),
                ("login_pw", models.CharField(max_length=20)),
            ],
        ),
    ]
