# Generated by Django 4.2.7 on 2023-11-24 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
