# Generated by Django 4.2.7 on 2023-11-24 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="init_user",
        ),
    ]
