# Generated by Django 4.2.7 on 2023-11-24 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0003_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
