# Generated by Django 4.2.7 on 2023-11-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_id",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_pw",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
