# Generated by Django 4.2.7 on 2023-11-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0005_alter_user_login_id_alter_user_login_pw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="factor",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
