# Generated by Django 4.2.7 on 2023-11-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0006_alter_user_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(max_length=2),
        ),
    ]
