# Generated by Django 4.2.7 on 2023-11-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0007_alter_user_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
