# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0008_user_username_alter_user_login_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hello",
            field=models.TextField(null=True),
        ),
    ]
