# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0009_user_hello"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hello",
        ),
    ]
