# Generated by Django 4.2.7 on 2023-11-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0010_remove_user_hello"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scents",
            fields=[
                (
                    "scent_name",
                    models.CharField(
                        db_column="향의 종류",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scent_name_dropdown", models.TextField(db_column="분류")),
                ("link_img", models.CharField(db_column="사진", max_length=255)),
            ],
            options={
                "db_table": "scent_select",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="golajum_done",
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("date_golajum", models.DateTimeField(auto_now_add=True)),
                ("date_rated", models.DateTimeField(null=True)),
                ("rating", models.IntegerField(null=True)),
                ("sweet_rating", models.IntegerField(default=0)),
                ("sour_rating", models.IntegerField(default=0)),
                ("fizzy_rating", models.IntegerField(default=0)),
                ("body_rating", models.IntegerField(default=0)),
                ("strong_rating", models.IntegerField(default=0)),
                ("alc_type_rating", models.TextField(default=[])),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="init.user"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="init.output"
                    ),
                ),
            ],
        ),
    ]
