# Generated by Django 4.2.7 on 2023-11-30 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0011_scents_user_golajum_done_alter_user_username_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="golajum_done",
        ),
    ]
