# Generated by Django 4.2.7 on 2023-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0012_remove_user_golajum_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="alc_type_rating",
        ),
        migrations.AddField(
            model_name="log",
            name="alc_range_rating",
            field=models.IntegerField(default=0),
        ),
    ]
