# Generated by Django 4.2.7 on 2023-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0013_remove_log_alc_type_rating_log_alc_range_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="date_checked",
            field=models.DateTimeField(null=True),
        ),
    ]
