# Generated by Django 4.2.7 on 2023-11-30 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0014_log_date_checked"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
