# Generated by Django 4.2.7 on 2023-11-30 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0016_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
