# Generated by Django 4.2.7 on 2023-11-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0017_delete_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("date_golajum", models.DateTimeField()),
                ("date_checked", models.DateTimeField(blank=True, null=True)),
                ("date_rated", models.DateTimeField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("sweet_rating", models.IntegerField()),
                ("sour_rating", models.IntegerField()),
                ("fizzy_rating", models.IntegerField()),
                ("strong_rating", models.IntegerField()),
                ("alc_range_rating", models.IntegerField()),
            ],
            options={
                "db_table": "log",
                "managed": False,
            },
        ),
    ]
