# Generated by Django 4.2.7 on 2023-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init", "0018_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Golajum",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("login_id", models.CharField(blank=True, max_length=45, null=True)),
                ("alc_type", models.CharField(blank=True, max_length=45, null=True)),
                ("golm", models.TextField(blank=True, null=True)),
                ("factor", models.CharField(blank=True, max_length=45, null=True)),
                ("scent", models.TextField(blank=True, null=True)),
                (
                    "alc_range_bool",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "CE_good_bool",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("golajum", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "golajum",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
