# Generated by Django 4.2.7 on 2023-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("date_golajum", models.DateTimeField()),
                ("date_rated", models.DateTimeField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("sweet_rating", models.IntegerField()),
                ("sour_rating", models.IntegerField()),
                ("fizzy_rating", models.IntegerField()),
                ("body_rating", models.IntegerField()),
                ("strong_rating", models.IntegerField()),
                ("alc_type_rating", models.TextField()),
            ],
            options={
                "db_table": "init_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scents",
            fields=[
                (
                    "scent_name",
                    models.CharField(
                        db_column="향의 종류",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scent_name_dropdown", models.TextField(db_column="분류")),
                ("link_img", models.CharField(db_column="사진", max_length=255)),
            ],
            options={
                "db_table": "scent_select",
                "managed": False,
            },
        ),
    ]
