# Generated by Django 4.2.7 on 2023-11-30 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_log_scents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={},
        ),
    ]
