# Generated by Django 4.2.7 on 2023-11-30 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_log_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={},
        ),
    ]
