# Generated by Django 4.2.7 on 2023-11-30 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_log_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
