# Generated by Django 4.2.7 on 2023-12-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Golajum",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("login_id", models.CharField(blank=True, max_length=45, null=True)),
                ("alc_type", models.CharField(blank=True, max_length=45, null=True)),
                ("golm", models.TextField(blank=True, null=True)),
                ("dscb", models.TextField(blank=True, null=True)),
                ("factor", models.CharField(blank=True, max_length=45, null=True)),
                ("scent", models.TextField(blank=True, null=True)),
                (
                    "alc_range_bool",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "CE_good_bool",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("golajum", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "golajum",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "site",
                "managed": False,
            },
        ),
    ]
