# Generated by Django 4.2.7 on 2023-12-13 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_location_delete_site"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="location",
        ),
    ]
