# Generated by Django 4.2.7 on 2023-12-13 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_location_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="shoplocation",
        ),
    ]
